services:
  products.api:
    container_name: Products.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
    ports:
      - "8081:8081"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: always
    networks:
      - internal-docker-network

  sqlserver:
    container_name: Products.SQLServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SA_passw0rd
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SA_passw0rd", "-Q", "SELECT 1", "-C"]
      interval: 5s
      timeout: 5s 
      retries: 20 
      start_period: 10s
    restart: always
    networks:
      - internal-docker-network

networks:
  internal-docker-network:
    driver: bridge

volumes:
  sql_data: